repos:
  - repo: https://github.com/pycqa/flake8
    rev: '7.1.1'
    hooks:
      - id: flake8

  - repo: https://github.com/commitizen-tools/commitizen
    rev: 'v4.1.1'
    hooks:
      - id: commitizen
        stages: [commit-msg]
        args: ["--commit-msg-file"]
