services:
  app:
    image: inv-bot-image
    build:
      dockerfile: Dockerfile
      context: .
    container_name: inv-bot-compose
    volumes:
      - ./staticfiles:/app/staticfiles
      - crm:app/srm
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: make run

volumes:
  crm:
