services:
  app:
    image: inv-bot-image
    build:
      dockerfile: Dockerfile
      context: .
    container_name: inv-bot-compose
    volumes:
      - ./staticfiles:/app/staticfiles
      - crm:/app/crm
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - ${BOT_TOKEN}
      - ${ADMIN1_ID}
      - ${ADMIN2_ID}
      - ${CHANNEL_ID}
      - ${CHANNEL1_TO_CHECK}
      - ${CHANNEL2_TO_CHECK}
    command: make run

volumes:
  crm:
