name: CD

on:
  push:
    branches: ["inviting-bot-without-screenshot-validation-feature"]

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

#      - name: Log in to GitHub Container Registry
#        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
#
#      - name: Build Docker Image
#        run: docker compose up --build
#
#      - name: Push Docker Image
#        run: docker push inv-bot-image:latest

      - name: Deploy to Remote Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: whoami
